<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alin Sever">
<meta name="dcterms.date" content="2025-10-16">

<title>Linear Regression Analysis - Predicting Body Mass Index – Portfolio - Alin Sever</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/alin.png" alt="" class="navbar-logo light-content">
    <img src="../../assets/alin.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Alin Sever</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ml-portfolio/index.html">ML Portfolio</a></li><li class="breadcrumb-item"><a href="../../ml-portfolio/02_nhanes_R/index.html">NHANES - R Project</a></li><li class="breadcrumb-item"><a href="../../ml-portfolio/02_nhanes_R/01_linear_model.html">Linear Regression Analysis - Predicting Body Mass Index</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">ML Portfolio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ml-portfolio/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../ml-portfolio/01_labs_R/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Labs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ml-portfolio/01_labs_R/04_svm/svm_lab_iris.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Support Vector Machine (Lab)</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../ml-portfolio/02_nhanes_R/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NHANES - R Project</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ml-portfolio/02_nhanes_R/01_linear_model.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Linear Regression Analysis - Predicting Body Mass Index</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ml-portfolio/02_nhanes_R/02_support_vector_machine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting Obesity using Support Vector Machines</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ml-portfolio/03_diabetes_python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diabetes Readmission - Python</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Standalone Projects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../standalone-projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../standalone-projects/bitcoin_portfolio_R/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bitcoin Portfolio (R)</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../standalone-projects/swiss_electricity_transition_R/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Swiss Electricity Transition (R)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../standalone-projects/swiss_electricity_transition_R/Swiss_Electricity_Transition_Project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Swiss Electricity System Under Transition</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Courses &amp; Certificates</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-linear-modeling" id="toc-introduction-to-linear-modeling" class="nav-link active" data-scroll-target="#introduction-to-linear-modeling"><span class="header-section-number">1</span> Introduction to Linear Modeling</a>
  <ul>
  <li><a href="#linear-models-for-bmi" id="toc-linear-models-for-bmi" class="nav-link" data-scroll-target="#linear-models-for-bmi"><span class="header-section-number">1.1</span> Linear Models for BMI</a></li>
  <li><a href="#model-specifications" id="toc-model-specifications" class="nav-link" data-scroll-target="#model-specifications"><span class="header-section-number">1.2</span> Model Specifications</a></li>
  <li><a href="#reasearch-questions" id="toc-reasearch-questions" class="nav-link" data-scroll-target="#reasearch-questions"><span class="header-section-number">1.3</span> Reasearch Questions</a></li>
  </ul></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing"><span class="header-section-number">2</span> Data processing</a></li>
  <li><a href="#exploratory-analysis-eda" id="toc-exploratory-analysis-eda" class="nav-link" data-scroll-target="#exploratory-analysis-eda"><span class="header-section-number">3</span> Exploratory Analysis (EDA)</a>
  <ul>
  <li><a href="#outcome-distribution-bmi" id="toc-outcome-distribution-bmi" class="nav-link" data-scroll-target="#outcome-distribution-bmi"><span class="header-section-number">3.1</span> Outcome distribution (BMI)</a></li>
  <li><a href="#summary-of-exploratory-data-analysis-bmi-vs-predictors" id="toc-summary-of-exploratory-data-analysis-bmi-vs-predictors" class="nav-link" data-scroll-target="#summary-of-exploratory-data-analysis-bmi-vs-predictors"><span class="header-section-number">3.2</span> Summary of Exploratory Data Analysis BMI vs predictors</a></li>
  </ul></li>
  <li><a href="#linear-model" id="toc-linear-model" class="nav-link" data-scroll-target="#linear-model"><span class="header-section-number">4</span> Linear Model</a>
  <ul>
  <li><a href="#adding-interactions" id="toc-adding-interactions" class="nav-link" data-scroll-target="#adding-interactions"><span class="header-section-number">4.5</span> Adding Interactions</a></li>
  </ul></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">5</span> Research Questions</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="01_linear_model.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ml-portfolio/index.html">ML Portfolio</a></li><li class="breadcrumb-item"><a href="../../ml-portfolio/02_nhanes_R/index.html">NHANES - R Project</a></li><li class="breadcrumb-item"><a href="../../ml-portfolio/02_nhanes_R/01_linear_model.html">Linear Regression Analysis - Predicting Body Mass Index</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Linear Regression Analysis - Predicting Body Mass Index</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alin Sever </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 16, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-to-linear-modeling" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-to-linear-modeling"><span class="header-section-number">1</span> Introduction to Linear Modeling</h2>
<p><strong>The goal is to explain wich factors are associated with BMI in US adults</strong> (NHANES dataset), controling for demographics (age, gender, race, education), socio-economic indicators (education, income) and lifestyle (sleep, physical activity, alcohol, smoking). We will start simple and incrementally extend to a multiple linear regression, also adding multiple regression effects that are conditional on the other covariates in the model.</p>
<section id="linear-models-for-bmi" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="linear-models-for-bmi"><span class="header-section-number">1.1</span> Linear Models for BMI</h3>
<p>Body Mass Index (BMI) is a continuous variable calculated as weight (kg) divided by height squared (<span class="math inline">\(m^{2}\)</span>). BMI is a proxy for body fat and is strongly related to chronic diseases such as diabetes, cardiovascular disease and hypertension.</p>
<p>In this analysis, we use NHANES adult participants (Age &gt;= 18) to examine how demographics, socioeconomic status and lifestyle behaviors are associated withBMI</p>
</section>
<section id="model-specifications" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="model-specifications"><span class="header-section-number">1.2</span> Model Specifications</h3>
<p>We model BMI as a linear function of selected predictors:</p>
<p>BMI = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span> * Age + <span class="math inline">\(\beta_2\)</span> * Gender + <span class="math inline">\(\beta_3\)</span> * Race + <span class="math inline">\(\beta_4\)</span> * Education + <span class="math inline">\(\beta_5\)</span> * log(Income) + <span class="math inline">\(\beta_6\)</span> * PhysActive + <span class="math inline">\(\beta_7\)</span> * SleepHrs + <span class="math inline">\(\beta_8\)</span> * SmokeNow + <span class="math inline">\(\beta_8\)</span> * AlcoholDay + <span class="math inline">\(\epsilon\)</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the intercept (BMI)</li>
<li><span class="math inline">\(\beta_1\)</span>…<span class="math inline">\(\beta_8\)</span> are the regression coefficients representing the effect on each predictor.</li>
<li><span class="math inline">\(\epsilon\)</span> represents the random error term (assumed that it is normally distributed)</li>
</ul>
</section>
<section id="reasearch-questions" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="reasearch-questions"><span class="header-section-number">1.3</span> Reasearch Questions</h3>
<ul>
<li>After adjusting for covariates, how does BMI vary with Age?</li>
<li>Do demographic factors (Gender, Race, Education) show overall association with BMI?</li>
<li>Are lifestyle factors (PsyActive, AlcoholDay, SleepNight, SmokeNow) associated with BMI, and how much?</li>
<li>How much variance is explained by the model?</li>
</ul>
</section>
</section>
<section id="data-processing" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-processing"><span class="header-section-number">2</span> Data processing</h2>
<ul>
<li>Population: NHANES adults (Age <span class="math inline">\(\geqslant\)</span> 18).</li>
<li>Variables: Age; Gender; Race1; Education; HHIncomeMid (we used log transform); PhysActive; SleepHrsNight; AlcoholDay; SmokeNow; BPSysAve. Factor coding: treatment contrasts (reference vs others).</li>
<li>Missing data strategy (baseline): Complete-case analysis on these variables to keep the workflow transparent.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Handling Missing Values">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Handling Missing Values
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We included only adults (≥ 18 years). BMI in children is interpreted with age- and sex-specific percentiles, so combining adults and minors would yield non-comparable BMI categories and biased estimates. We created log_income = log(HHIncomeMid). We then used a complete-case dataset for baseline modeling (all variables observed), retaining 27.5% of the adult sample.</p>
<p>AlcoholDay/SmokeNow are driving most most of the loss.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Percentage of Missing Values</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percent_Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SmokeNow</td>
<td style="text-align: right;">57.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">AlcoholDay</td>
<td style="text-align: right;">34.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HHIncomeMid</td>
<td style="text-align: right;">8.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_income</td>
<td style="text-align: right;">8.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BPSysAve</td>
<td style="text-align: right;">3.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI</td>
<td style="text-align: right;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">SleepHrsNight</td>
<td style="text-align: right;">0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race1</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">PhysActive</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exploratory-analysis-eda" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="exploratory-analysis-eda"><span class="header-section-number">3</span> Exploratory Analysis (EDA)</h2>
<section id="outcome-distribution-bmi" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="outcome-distribution-bmi"><span class="header-section-number">3.1</span> Outcome distribution (BMI)</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Summary statistics: mean, median, SD, quantiles:</strong></p>
<p>The response variable, Body Mass Index (BMI), ranged from 15.0 to 81.2 kg/m² with a mean of 28.8 kg/m² (SD = 6.65, median = 27.8).</p>
<p>Approximately 33% of participants were classified as overweight (25 ≤ BMI &lt; 30) and 33% as obese (BMI ≥ 30), reflecting the high prevalence of excess weight in the U.S. adult population.</p>
<p>The distribution exhibited moderate right skewness (skewness = 1.2), indicating a longer tail with high BMI values</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Descriptive Statistics for BMI</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">IQR</th>
<th style="text-align: right;">Skewness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">28.3</td>
<td style="text-align: right;">27.3</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">67.8</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">31.6</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">1.2</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Distribution of BMI Categories</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">BMI Category</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Patient Count</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percentage (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Underweight</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Normal</td>
<td style="text-align: right;">652</td>
<td style="text-align: right;">31.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overweight</td>
<td style="text-align: right;">687</td>
<td style="text-align: right;">33.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Obese</td>
<td style="text-align: right;">686</td>
<td style="text-align: right;">33.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="BMI Distribution plot and outlier detection">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>BMI Distribution plot and outlier detection
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Distribution plot of BMI (histogram + density curve)</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>The distribution of the BMI variable is right-skweed as shown in the overview. This shows that most people are around the average BMI in the data; however, some have very high BMI</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/distribution_BMI-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p>The box plot indicates that there are no outliners in the lower part ofthe distribution. The lower threshold is at approximately 13, while the upper threshold is approximately at 43.</p>
<p>In contrast the upper tail displays a substantial number of extreme values, with 43 observations identified as outliers.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/print_p3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>Although the BMI distribution shows high-value observations, these values fall within plausible physiological ranges for the NHANES population. Therefore, no outliers were removed.</p>
</div>
</div>
</div>
</section>
<section id="summary-of-exploratory-data-analysis-bmi-vs-predictors" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="summary-of-exploratory-data-analysis-bmi-vs-predictors"><span class="header-section-number">3.2</span> Summary of Exploratory Data Analysis BMI vs predictors</h3>
<p>Among all variables examined, physical activity, race/ethnicity, and education level showed the strongest associations with BMI. Physically active individuals had noticeably lower BMI on average, and several race and education groups displayed meaningful mean differences. In contrast, most continuous predictors such as age, income, sleep hours, blood pressure, and alcohol use—showed very weak correlations and offered limited linear explanatory power. Please see below in the collapsed section for the full EDA.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Pairwise relationships with BMI">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Pairwise relationships with BMI
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="pairwise-relationships-with-bmi-continuous-predictors" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="pairwise-relationships-with-bmi-continuous-predictors"><span class="header-section-number">3.3</span> Pairwise relationships with BMI (continuous predictors)</h3>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<p><strong>BMI vs Age</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>The scatterplot with a LOESS smoother shows that BMI remains largely consistent across age groups. The Pearson correlation coefficient (r = 0.0144721) indicates virtually no linear association between age and BMI.</p>
<p>The corresponding coefficient of determination (<span class="math inline">\(R^{2}\)</span> = 0.0002094) confirms that age explains less than 0.02% of the variance in BMI. This suggests that BMI is not influenced by age in this sample, and other demographic or lifestyle variables likely play a more substantial role in determining BMI.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/bmi_vs_age_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>BMI vs log(income)</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>The scatterplot with a LOESS smoother shows a weak negative association between BMI and the logarithm of household income.</p>
<p>The Pearson correlation coefficient (r = -0.0504988) confirms that higher income is associated with slightly lower BMI values. However, this relationship is very weak (<span class="math inline">\(R^{2}\)</span> = 0.00255), indicating that household income explains less than 1% of the variance in BMI.</p>
<p>Although the direction aligns with the expected negative relationship for higher income, the effect size suggests that income has minimal influence on BMI in this sample.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/plot_incom-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<p><strong>BMI vs Sleep</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>BMI shows a negligible linear association with sleep duration (r = -0.0321021; <span class="math inline">\(R^{2}\)</span> ≈ 0.001031).</p>
<p>The LOESS smoother suggests a shallow U-shape, with the lowest BMI at approximately 7.5 hours of sleep and slightly higher BMI at both shorter and longer durations.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/plot_sleep-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>BMI vs Systolic Blood Presure</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Although we expected a strong positive relashionship between BMI and systolic blood pressure, the data shows only a very week positive trend. The LOESS curve suggests a small increase in BP with BMI initially, but then the relashioship plateus and even goes down slightly. This indicates that systolic blood presure alone is not a predictor in this sample.</p>
<p>BMI is expected to predict high blood pressure, but the data may not show this since many patients manage their blood pressure with medication.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/blood_resure_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<p><strong>BMI vs AlcoholDay</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>The LOESS curve is nearly flat with a slight downward tilt. The confidence interval widens as AlcoholDay increases (due to few observations with higher values) The unajusted linear correlation is appox 0.03, meaning very little to no association with BMI.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/alcohol-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Appendinx: BMI vs Alcohol Day">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Appendinx: BMI vs Alcohol Day
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Below are the BMI–AlcoholDay correlations and visualizations: (i) the plot over the full 0–80 range, and (ii) the log(1 + AlcoholDay)</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>cor_alc <span class="ot">&lt;-</span> <span class="fu">cor</span>(nhanes_lm<span class="sc">$</span>AlcoholDay, nhanes_lm<span class="sc">$</span>BMI)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>cor_alc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03483019</code></pre>
</div>
</div>
<p><strong>(i) the plot over the full 0–80 range</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/plot_alc_fullrange-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>(ii) the log(1 + AlcoholDay)</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/plot_alc_log-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0240489</code></pre>
</div>
</div>
<p>The correlation between alcohol and BMI is even smaller when AlcoholDay is logaritmized - 0.0240489.</p>
</div>
</div>
</div>
</section>
<section id="bmi-vs-categorical-predictors" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="bmi-vs-categorical-predictors"><span class="header-section-number">3.4</span> BMI vs Categorical predictors</h3>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<p><strong>BMI by Gender</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>&nbsp;</p>
<p>In this sample the average for female and male is almost the same; however, the BMI distribution is also more variable among females, as indicated by a higher standard deviation (sd = 7.04 vs.&nbsp;5.43). There is <em>no evidence</em> that gender plays a strong role in explaining BMI differences in this sample.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/p_gender2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>BMI by Physical Activity</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>On average, individuals that reported being physically active have a lower BMI (mean ≈ 27.9 kg/<span class="math inline">\(m^{2}\)</span>) than those who are not (mean ≈ 29.9 kg/<span class="math inline">\(m^{2}\)</span>). There is very strong evidence for a difference in BMI between physically active and inactive individuals (p &lt; 2.2 × <span class="math inline">\(10^{-16}\)</span>), with an estimated mean difference of approximately 2.0 units (95% CI: [1.68, 2.36] kg/<span class="math inline">\(m^{2}\)</span>). BMI is also more variable among inactive individuals (SD = 6.9 vs.&nbsp;5.3), indicating a wider spread of body weight outcomes in this group.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/p_active_2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Appendix: Physical Activity Stats and T-test">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Appendix: Physical Activity Stats and T-test
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Descriptive Statistics for Physical Active</caption>
<thead>
<tr class="header">
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean_BMI</th>
<th style="text-align: right;">SD_BMI</th>
<th style="text-align: right;">Median_BMI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">989</td>
<td style="text-align: right;">29.2</td>
<td style="text-align: right;">6.9</td>
<td style="text-align: right;">28.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1071</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">5.3</td>
<td style="text-align: right;">26.6</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  BMI by PhysActive
t = 6.6975, df = 1847.8, p-value = 2.805e-11
alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
95 percent confidence interval:
 1.285537 2.350209
sample estimates:
 mean in group No mean in group Yes 
         29.22283          27.40496 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<p><strong>BMI vs Education</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>In this sample, individuals who reported having a Colledge Graduate had a lower mean (mean ≈ 27.1 kg/<span class="math inline">\(m^{2}\)</span>) compared with rest of the groups (mean ≈ 28.2 - 29.2 kg/<span class="math inline">\(m^{2}\)</span>). The one-way ANOVA test provides strong evidence that the mean BMI differs across education levels (p &lt; 0.001). However the coefficient of deteermination R2 = 0.0126791 indicates that the education level only explains 1.3% in the BMI variation. This means that, while the difference is statistically significant, its practical importance is very small.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/education_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Appendix: Education Stats and Anova and ">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Appendix: Education Stats and Anova and
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Descriptive Statistics for Education</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Education</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean_BMI</th>
<th style="text-align: right;">SD_BMI</th>
<th style="text-align: right;">Median_BMI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">8th Grade</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">29.2</td>
<td style="text-align: right;">6.9</td>
<td style="text-align: right;">27.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 - 11th Grade</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">28.9</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">27.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">690</td>
<td style="text-align: right;">28.7</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: right;">27.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">High School</td>
<td style="text-align: right;">491</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">27.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">College Grad</td>
<td style="text-align: right;">486</td>
<td style="text-align: right;">27.1</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">26.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Anova</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Education      4    990   247.4   6.598 2.84e-05 ***
Residuals   2055  77068    37.5                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Tukey</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = BMI ~ Education, data = nhanes_lm)

$Education
                                  diff       lwr         upr     p adj
9 - 11th Grade-8th Grade    -0.2721042 -2.249181  1.70497290 0.9957664
High School-8th Grade       -1.0267140 -2.909063  0.85563478 0.5696549
Some College-8th Grade      -0.4749704 -2.313186  1.36324503 0.9553039
College Grad-8th Grade      -2.0699378 -3.953842 -0.18603377 0.0229035
High School-9 - 11th Grade  -0.7546099 -1.981100  0.47188025 0.4467253
Some College-9 - 11th Grade -0.2028662 -1.360483  0.95475066 0.9893126
College Grad-9 - 11th Grade -1.7978337 -3.026709 -0.56895799 0.0006415
Some College-High School     0.5517436 -0.435414  1.53890127 0.5455991
College Grad-High School    -1.0432238 -2.113055  0.02660738 0.0600524
College Grad-Some College   -1.5949674 -2.585087 -0.60484745 0.0001120</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/edd2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>BMI by Race</strong></p>
<p>&nbsp;</p>
<p>In this sample Black and Mexican groups show higher average BMI than White, while “Other” is lower; the boxplots (red diamonds = means) reflect these shifts.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/race2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Appendinx: Race Stats and Anova">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Appendinx: Race Stats and Anova
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Race1        n Mean_BMI SD_BMI Median_BMI
  &lt;fct&gt;    &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 Black      187     30.7   8.82       28.6
2 Mexican    125     30.6   5.72       30.0
3 Hispanic    83     28.3   4.79       27.1
4 White     1561     27.9   5.78       27  
5 Other      104     26.7   5.71       25.2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
   aov(formula = BMI ~ Race1, data = nhanes_lm)

Terms:
                   Race1 Residuals
Sum of Squares   2263.28  75794.92
Deg. of Freedom        4      2055

Residual standard error: 6.073152
Estimated effects may be unbalanced</code></pre>
</div>
</div>
<p>One-way ANOVA indicates a significant overall difference across Race1 (p &lt; 0.001); pairwise Tukey comparisons can then identify which specific pairs differ.</p>
</div>
</div>
</div>
<div class="box" style="background-color:#f9f9f9; padding:15px; border-radius:10px;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>BMI vs Smoke</strong></p>
<p>Smokers show an approximate 1.1 kg/<span class="math inline">\(m^{2}\)</span> lower mean BMI than non-smokers. The T-test result tells us that there is very strong evidence that the median BMI between non-smokers and smokers is not zero.(appendix)</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_linear_model_files/figure-html/smoke-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Appendix: BMI~Smoke t-test">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Appendix: BMI~Smoke t-test
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>t_test_Smoke <span class="ot">&lt;-</span> <span class="fu">t.test</span>(BMI <span class="sc">~</span> SmokeNow, <span class="at">data =</span> nhanes_lm)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>t_test_Smoke</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  BMI by SmokeNow
t = 4.1853, df = 1947.8, p-value = 2.974e-05
alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
95 percent confidence interval:
 0.6065475 1.6762202
sample estimates:
 mean in group No mean in group Yes 
         28.79577          27.65439 </code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="linear-model" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="linear-model"><span class="header-section-number">4</span> Linear Model</h2>
<p><strong>Summary of Linear Modeling Progression (Collapsed Below)</strong></p>
<p>To reach the final interaction model, we estimated a sequence of nested linear models. The simple BMI ~ Age regression showed no meaningful association, and adding basic demographics improved the fit only slightly, with race contributing the most. Socioeconomic factors provided minimal additional explanatory power. Lifestyle and clinical variables strengthened the model somewhat, with physical activity, smoking status, systolic blood pressure, and race emerging as the most consistent predictors of BMI. All earlier models and their outputs are collapsed below, while the final interaction model remains visible for interpretation.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Linear Modeling Progression">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Linear Modeling Progression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="bmi-age" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="bmi-age"><span class="header-section-number">4.1</span> BMI ~ Age</h3>
<p>We are starting with a simpler linear model</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>The intercept is 28.01 kg/<span class="math inline">\(m^{2}\)</span>. The interpretation has no meaning as it represents the BMI at age 0 for an adult. (part of the linear fit)</p>
<p>The slope is 0.005 kg/<span class="math inline">\(m^{2}\)</span> and the interpretation would be that for the each year increase the BMI will increase with 0.005. The p value is 0.512 and we can say that in this linear model there is no evidence of a linear assocciation between BMI and Age.</p>
<p>With a fit <span class="math inline">\(R^{2}\)</span> = 0.0002 (adj. <span class="math inline">\(R^{2}\)</span> = -0.0002) Age explaines none of the variability in BMI</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m_age <span class="ot">&lt;-</span><span class="fu">lm</span>(BMI <span class="sc">~</span> Age, <span class="at">data =</span> nhanes_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(m_age)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>age_sum <span class="ot">&lt;-</span> <span class="fu">tidy</span>(m_age, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#age_sum</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>age_fit <span class="ot">&lt;-</span> <span class="fu">glance</span>(m_age)[, <span class="fu">c</span>(<span class="st">"r.squared"</span>,<span class="st">"adj.r.squared"</span>,<span class="st">"sigma"</span>,<span class="st">"nobs"</span>)]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(age_sum, <span class="at">digits=</span><span class="dv">3</span>, <span class="at">caption=</span><span class="st">"BMI ~ Age: coefficient table (with 95% CI)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>BMI ~ Age: coefficient table (with 95% CI)</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">28.018</td>
<td style="text-align: right;">0.418</td>
<td style="text-align: right;">67.033</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">27.198</td>
<td style="text-align: right;">28.838</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: right;">0.512</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.022</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#kable(age_fit, digits=3, caption="BMI ~ Age: model fit")</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>age_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  r.squared adj.r.squared sigma  nobs
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  0.000209     -0.000276  6.16  2060</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="model-1-demographic" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="model-1-demographic"><span class="header-section-number">4.2</span> Model 1: Demographic</h3>
<p>We will add core demographic variables to the model: Age + Gender + Race</p>
<p><strong>Model:</strong> BMI ~ Age + Gender + Race</p>
<blockquote class="blockquote">
<p>We fit a multiple linear model with BMI as the response and Age (continuous), Gender (female = reference), and Race (White = reference) as covariates.</p>
</blockquote>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BMI <span class="sc">~</span> Age <span class="sc">+</span> Gender <span class="sc">+</span> Race1, <span class="at">data =</span> nhanes_lm)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BMI ~ Age + Gender + Race1, data = nhanes_lm)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.210  -4.209  -0.949   3.436  40.186 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   27.117470   0.463686  58.482  &lt; 2e-16 ***
Age            0.013510   0.008406   1.607   0.1082    
Gendermale     0.221968   0.272635   0.814   0.4156    
Race1Black     2.872157   0.472655   6.077 1.46e-09 ***
Race1Mexican   2.802671   0.571678   4.903 1.02e-06 ***
Race1Other    -1.131178   0.619031  -1.827   0.0678 .  
Race1Hispanic  0.446401   0.688336   0.649   0.5167    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.071 on 2053 degrees of freedom
Multiple R-squared:  0.03055,   Adjusted R-squared:  0.02772 
F-statistic: 10.78 on 6 and 2053 DF,  p-value: 7.701e-12</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients with 95% CIs (t-tests)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># core_coef &lt;- broom::tidy(M1, conf.int = TRUE)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># core_coef</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># M1_sum &lt;- tidy(M1, conf.int = TRUE)</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># kable(M1_sum, digits=3, caption="BMI ~ Age + Gender + Race coefficient table (with 95% CI)")</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Model fit</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># M1_fit  &lt;- broom::glance(M1)[, c("r.squared","adj.r.squared","sigma","df","nobs")]</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># knitr::kable(M1_fit,  digits = 3, caption = "Core model: fit statistics")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>In this model the Race differences between groups relative to White: Black (+ 2.87 kg/<span class="math inline">\(m^{2}\)</span>, p &lt; <span class="math inline">\(10^{-8}\)</span>) and Mexican (+2.80 kg/<span class="math inline">\(m^{2}\)</span>, p &lt; <span class="math inline">\(10^{-6}\)</span>) participants have a higher BMI on average, while Other shows very weak evidence that the BMI is lower on everage than White (-1.13 kg/<span class="math inline">\(m^{2}\)</span>, p &lt; 0.068) and for Hispanix group there is no evidence that the BMI is different from White category on average (+0.45 kg/<span class="math inline">\(m^{2}\)</span>, p &lt; 0.517). The adjusted <span class="math inline">\(R^{2}\)</span> = 0.028, meaning that demographics only explain ~2.8% of BMI variability</p>
<p><strong>F-tests for M1 (BMI ~ Age + Gender + Race1)</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>M1_drop1 <span class="ot">&lt;-</span> <span class="fu">drop1</span>(M1, <span class="at">test =</span> <span class="st">"F"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>M1_drop1 </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
BMI ~ Age + Gender + Race1
       Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;              75673 7437.7                      
Age     1     95.20 75768 7438.3  2.5827    0.1082    
Gender  1     24.43 75698 7436.3  0.6629    0.4156    
Race1   4   2318.52 77992 7491.8 15.7252 1.109e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Using drop1() we test each term conditional on the others. Race is associated with BMI; Age and Gender are not, at this stage.</p>
</section>
<section id="adding-socioeconomic-factors" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="adding-socioeconomic-factors"><span class="header-section-number">4.3</span> Adding Socioeconomic factors</h3>
<p>We are adding socioeconomic factors to our model</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">update</span>(M1, . <span class="sc">~</span> . <span class="sc">+</span> Education <span class="sc">+</span> log_income)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BMI ~ Age + Gender + Race1 + Education + log_income, 
    data = nhanes_lm)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.858  -4.169  -0.913   3.454  39.780 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             28.034963   2.066514  13.566  &lt; 2e-16 ***
Age                      0.015941   0.008473   1.881   0.0601 .  
Gendermale               0.191993   0.272588   0.704   0.4813    
Race1Black               2.671400   0.481595   5.547 3.28e-08 ***
Race1Mexican             2.649685   0.593333   4.466 8.41e-06 ***
Race1Other              -1.077031   0.623601  -1.727   0.0843 .  
Race1Hispanic            0.344172   0.692346   0.497   0.6192    
Education9 - 11th Grade -0.030781   0.733418  -0.042   0.9665    
EducationHigh School    -0.621045   0.703421  -0.883   0.3774    
EducationSome College    0.164729   0.698290   0.236   0.8135    
EducationCollege Grad   -1.224686   0.723380  -1.693   0.0906 .  
log_income              -0.055827   0.185911  -0.300   0.7640    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.053 on 2048 degrees of freedom
Multiple R-squared:  0.03873,   Adjusted R-squared:  0.03357 
F-statistic: 7.501 on 11 and 2048 DF,  p-value: 9.159e-13</code></pre>
</div>
</div>
<p>Afteradding the Education and log_income as covariates the BMI remains higher forBlack and Mexican participants vs White. Age and particpats that are Colledge Graduates shows a very weak association with BMI. The adj. <span class="math inline">\(R^{2}\)</span> shows an explanability of 3.4%</p>
<p><strong>Term-wise F-tests</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>M2_drop1 <span class="ot">&lt;-</span> <span class="fu">drop1</span>(M2, <span class="at">test =</span> <span class="st">"F"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>M2_drop1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
BMI ~ Age + Gender + Race1 + Education + log_income
           Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;                  75035 7430.2                      
Age         1    129.68 75165 7431.8  3.5393  0.060071 .  
Gender      1     18.18 75053 7428.7  0.4961  0.481305    
Race1       4   1912.91 76948 7474.1 13.0527 1.687e-10 ***
Education   4    599.27 75634 7438.6  4.0891  0.002643 ** 
log_income  1      3.30 75038 7428.3  0.0902  0.763989    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Term-wise F-tests: BMI differs overall by Race and Education; Age is borderline; Gender and log(Income) show little added association (conditional on other covariates).</p>
</section>
<section id="adding-lifestyle-clinical-predictors" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="adding-lifestyle-clinical-predictors"><span class="header-section-number">4.4</span> Adding Lifestyle &amp; Clinical predictors</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>M3 <span class="ot">&lt;-</span> <span class="fu">update</span>(M2, . <span class="sc">~</span> . <span class="sc">+</span> PhysActive <span class="sc">+</span> SleepHrsNight <span class="sc">+</span> AlcoholDay <span class="sc">+</span> SmokeNow <span class="sc">+</span> BPSysAve)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BMI ~ Age + Gender + Race1 + Education + log_income + 
    PhysActive + SleepHrsNight + AlcoholDay + SmokeNow + BPSysAve, 
    data = nhanes_lm)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.915  -3.999  -0.831   3.537  37.748 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             29.573516   2.335666  12.662  &lt; 2e-16 ***
Age                     -0.015609   0.009670  -1.614 0.106648    
Gendermale               0.014294   0.274346   0.052 0.958454    
Race1Black               3.006900   0.476562   6.310 3.42e-10 ***
Race1Mexican             2.241999   0.584376   3.837 0.000129 ***
Race1Other              -0.531417   0.616321  -0.862 0.388656    
Race1Hispanic            0.416809   0.679956   0.613 0.539948    
Education9 - 11th Grade  0.089781   0.720029   0.125 0.900781    
EducationHigh School    -0.516741   0.690459  -0.748 0.454304    
EducationSome College    0.253163   0.685239   0.369 0.711830    
EducationCollege Grad   -0.926147   0.719078  -1.288 0.197904    
log_income              -0.110284   0.183536  -0.601 0.547982    
PhysActiveYes           -1.809196   0.278270  -6.502 9.96e-11 ***
SleepHrsNight           -0.082643   0.098545  -0.839 0.401770    
AlcoholDay               0.074228   0.041594   1.785 0.074476 .  
SmokeNowYes             -2.181678   0.299600  -7.282 4.67e-13 ***
BPSysAve                 0.022322   0.008524   2.619 0.008893 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.928 on 2043 degrees of freedom
Multiple R-squared:  0.08013,   Adjusted R-squared:  0.07293 
F-statistic: 11.12 on 16 and 2043 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>After adding lifestyle and clinical predictors to our Model BMI we can observe that BMI stays higher for Black and Mexican in comparision with White participants. Physically Active participants have a lower BMI, and Smoking participants have a lower BMI. Effects are conditional on the others (treatment coding); results are associations, not causal.</p>
<p><strong>Term-wise F-tests</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>M3_drop1 <span class="ot">&lt;-</span> <span class="fu">drop1</span>(M3, <span class="at">test =</span> <span class="st">"F"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>M3_drop1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
BMI ~ Age + Gender + Race1 + Education + log_income + PhysActive + 
    SleepHrsNight + AlcoholDay + SmokeNow + BPSysAve
              Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;                     71803 7349.5                      
Age            1     91.57 71895 7350.2  2.6055  0.106648    
Gender         1      0.10 71804 7347.5  0.0027  0.958454    
Race1          4   1852.00 73655 7394.0 13.1736 1.346e-10 ***
Education      4    430.36 72234 7353.8  3.0612  0.015826 *  
log_income     1     12.69 71816 7347.9  0.3611  0.547982    
PhysActive     1   1485.64 73289 7389.7 42.2705 9.962e-11 ***
SleepHrsNight  1     24.72 71828 7348.2  0.7033  0.401770    
AlcoholDay     1    111.93 71915 7350.7  3.1848  0.074476 .  
SmokeNow       1   1863.69 73667 7400.3 53.0269 4.673e-13 ***
BPSysAve       1    241.01 72044 7354.4  6.8573  0.008893 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Term-wise F-tests for M3 (BMI ~ Age + Gender + Race1 + Education + log_income + PhysActive + SleepHrsNight + AlcoholDay + SmokeNow + BPSysAve)</p>
</section>
</div>
</div>
</div>
<section id="adding-interactions" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="adding-interactions"><span class="header-section-number">4.5</span> Adding Interactions</h3>
<p>We extended the model with prespecified interactions to test whether the association between:</p>
<ul>
<li><strong>PhysActive × Gender</strong> - Based on <em>Gender Differences in Exercise Habits and Quality of Life Reports</em><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, physical activity patterns differ significantly by gender. Here we test whether the BMI–activity association varies by sex.</li>
<li><strong>PhysActive × Education</strong> - According to the research <em>Education leads to a more physically active lifestyle</em><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, <em>“one additional year of education leads to a 0.62-unit higher overall physical activity”</em>. We are testing if in our sample the activity–BMI association varies across socioeconomic factors (education levels).</li>
<li><strong>Gender × SmokeNow</strong> - Based on the report from <em>Swiss association for tabacco control</em><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, there are known gender differences in smoking paterns. In out sample we are testing whether the smoking-BMI association differs by sex.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>M4 <span class="ot">&lt;-</span> <span class="fu">update</span>(M3, . <span class="sc">~</span> . <span class="sc">+</span> PhysActive<span class="sc">:</span>Gender <span class="sc">+</span> PhysActive<span class="sc">:</span>Education <span class="sc">+</span> Gender<span class="sc">:</span>SmokeNow)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Model Summary-  result">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model Summary- result
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BMI ~ Age + Gender + Race1 + Education + log_income + 
    PhysActive + SleepHrsNight + AlcoholDay + SmokeNow + BPSysAve + 
    Gender:PhysActive + Education:PhysActive + Gender:SmokeNow, 
    data = nhanes_lm)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.168  -4.057  -0.895   3.396  37.770 

Coefficients:
                                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           27.726849   2.380324  11.648  &lt; 2e-16 ***
Age                                   -0.014841   0.009598  -1.546  0.12221    
Gendermale                             0.611595   0.482437   1.268  0.20504    
Race1Black                             2.890277   0.473409   6.105 1.23e-09 ***
Race1Mexican                           2.292266   0.580298   3.950 8.08e-05 ***
Race1Other                            -0.520097   0.611616  -0.850  0.39522    
Race1Hispanic                          0.585686   0.679784   0.862  0.38902    
Education9 - 11th Grade                1.154768   0.876821   1.317  0.18799    
EducationHigh School                  -0.145821   0.849861  -0.172  0.86378    
EducationSome College                  0.855728   0.839405   1.019  0.30811    
EducationCollege Grad                  0.269230   0.937998   0.287  0.77412    
log_income                            -0.065774   0.183019  -0.359  0.71935    
PhysActiveYes                         -0.262527   1.337241  -0.196  0.84438    
SleepHrsNight                         -0.099740   0.098131  -1.016  0.30956    
AlcoholDay                             0.084933   0.041469   2.048  0.04068 *  
SmokeNowYes                           -0.661655   0.433203  -1.527  0.12683    
BPSysAve                               0.025625   0.008505   3.013  0.00262 ** 
Gendermale:PhysActiveYes               1.084032   0.538843   2.012  0.04437 *  
Education9 - 11th Grade:PhysActiveYes -3.183134   1.482250  -2.148  0.03187 *  
EducationHigh School:PhysActiveYes    -1.531381   1.409680  -1.086  0.27746    
EducationSome College:PhysActiveYes   -2.013071   1.376690  -1.462  0.14383    
EducationCollege Grad:PhysActiveYes   -2.849886   1.435170  -1.986  0.04720 *  
Gendermale:SmokeNowYes                -2.650774   0.538496  -4.923 9.23e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.879 on 2037 degrees of freedom
Multiple R-squared:  0.09791,   Adjusted R-squared:  0.08817 
F-statistic: 10.05 on 22 and 2037 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Interaction observation:</strong></p>
<ul>
<li>Gender:SmokingNow: there is very strong evidence that smoking is linked to a lower BMI for both sexes: women ~ 0.7 kg/<span class="math inline">\(m^{2}\)</span> lower and men ~ 3.3 kg/<span class="math inline">\(m^{2}\)</span> compared with non-smokers.</li>
<li>PhysActivity:Gender: there is evidence that difference in average BMIassociated with physical acivity in not 0 men. In the baseline group women show a small decrease with activity (~ 0.3kg/<span class="math inline">\(m^{2}\)</span>). Men add approx 1.1 kg/<span class="math inline">\(m^{2}\)</span> to the female difference.</li>
<li>PhysActivity:Education: in lower (9–11) and higher (College) education groups, being active is associated with a noticeably lower BMI than in the 8th-grade group.</li>
</ul>
<blockquote class="blockquote">
<p>All of these interaction are conditional associations (not causal)</p>
</blockquote>
<p>As we added the interaction we oberve that AlcoholDay shows a small positive association with BMI (for each additional drink a day the BMI increases with 0.085 kg/<span class="math inline">\(m^{2}\)</span>, p = 0.04), conditional on other covariates.</p>
<p><strong>Term-wise F-tests</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>M4_drop1 <span class="ot">&lt;-</span> <span class="fu">drop1</span>(M4, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="F-test result">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>F-test result
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>M4_drop1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
BMI ~ Age + Gender + Race1 + Education + log_income + PhysActive + 
    SleepHrsNight + AlcoholDay + SmokeNow + BPSysAve + Gender:PhysActive + 
    Education:PhysActive + Gender:SmokeNow
                     Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;                            70416 7321.3                      
Age                   1     82.64 70498 7321.7  2.3907   0.12221    
Race1                 4   1759.80 72175 7364.2 12.7270 3.116e-10 ***
log_income            1      4.46 70420 7319.5  0.1292   0.71935    
SleepHrsNight         1     35.71 70451 7320.4  1.0330   0.30956    
AlcoholDay            1    145.00 70561 7323.6  4.1947   0.04068 *  
BPSysAve              1    313.77 70729 7328.5  9.0769   0.00262 ** 
Gender:PhysActive     1    139.91 70556 7323.4  4.0473   0.04437 *  
Education:PhysActive  4    263.23 70679 7321.0  1.9037   0.10719    
Gender:SmokeNow       1    837.64 71253 7343.7 24.2315 9.229e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Term-wise F-tests summary: BMI is associated with race, systolic BP, and shows effect modification for Gender:Smoking and Gender:Physical activity. Education:Physical activity is not supported</p>
</section>
</section>
<section id="research-questions" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">5</span> Research Questions</h2>
<p><strong>After adjusting for covariates, how does BMI vary with Age?</strong></p>
<p>Adjusted for all covariates, the term-wise F-test (drop1) shows little evidence of a linear association between age and BMI (p ≈ 0.12)</p>
<p><strong>Do demographic factors show overall association with BMI?</strong></p>
<ul>
<li><strong>Race/ethnicity:</strong> Yes. Strong overall association (clear F-test).</li>
<li><strong>Education:</strong> Yes (overall main effect), but no activity–education interaction.</li>
<li><strong>Gender:</strong> No large main effect, but gender modifies the associations of physical activity and smoking with BMI.</li>
</ul>
<p><strong>Are lifestile factors (PsyActive, AlcoholDay, SleepNight, SmokeNow) associated with BMI, and how much?</strong></p>
<ul>
<li>At the reference education (8th Grade), females show a small reduction with activity (PhysActive main term).</li>
<li>Males add the Gender:PhysActive interaction, show an increase with activity.</li>
<li>In 9–11th Grade and College Grad, the Education:PhysActive interactions are negative, showing that there is an associated reduction than in the reference education. However with the Drop1 test there is weak to no evidence that there is an interaction bewteen Education and PhyActive</li>
</ul>
<p><strong>How much variance is explained by the model?</strong></p>
<p>The model’s adjusted <span class="math inline">\(R^{2}\)</span> ≈ 0.088, so the model explains only 8.8% of the variability in BMI.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>See <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5033515/">PMC article</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>See <a href="https://pubmed.ncbi.nlm.nih.gov/32176397/">PMC article</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>See <a href="https://www.at-schweiz.ch/en/knowledge/data-figures/tobacco-consumption-in-switzerland/prevalence-in-general-population/">AT report</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/alinsever\.github\.io\/portfolio\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>